name: Go

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:

            -   name: Set up Go
                uses: actions/setup-go@v1
                with:
                    go-version: 1.14
                id: go

            -   name: Check out code into the Go module directory
                uses: actions/checkout@v2

            -   name: Get dependencies
                run: |
                    go get -v -t -d ./...
                    go get -u golang.org/x/lint/golint

            -   name: Test
                run: make test

            -   name: Build
                run: make build

            -   name: Deploy
                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
                    HOST: ${{ secrets.HOST }}
                    USERNAME: ${{ secrets.USERNAME }}
                    PASSWORD: ${{ secrets.PASSWORD }}
                run: |
                    echo "" > ".env"
                    echo "$HOST" >> ".env"
                    echo "$USERNAME" >> ".env"
                    echo "$PASSWORD" >> ".env"

                    echo "$DEPLOY_KEY" > deploy_key
                    chmod 600 deploy_key
                    ssh -i deploy_key -o StrictHostKeyChecking=no "root@$HOST" 'systemctl stop web-chat.service'
                    rsync -r -e 'ssh -i deploy_key -o StrictHostKeyChecking=no' --files-from=deploy_files . "root@$HOST:/web-chat"
                    ssh -i deploy_key -o StrictHostKeyChecking=no "root@$HOST" 'systemctl start web-chat.service'
